/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      display: ['ruby-text'],
      fontFamily: {
        switzer: ["Switzer", "sans-serif"],
        helvetica: ["Helvetica Rounded LT Std", "sans-serif"],
      },
      backgroundImage: {
        "best-shipping": "url('/images/shipping-rates.webp')",
        "download-app": "url('/images/download-app-background.webp')",
        "banner-1": "url('/images/banner-bg-1.webp')",
        "banner-2": "url('/images/banner-bg-2.webp')",
        "banner-3": "url('/images/banner-bg-3.webp')",
        "track-order": "url('/images/track-order.webp')",
        business: "url('/images/business.webp')",
        customGradientBg: "linear-gradient(180deg ,rgba(217, 217, 217, 0.4) 0%,rgba(255, 255, 255, 0.6) 50%)"
      },
      backgroundColor: {
        theme: "#00538C",
        cardTheme: "#F4F4F4",
        baseColor: "#F8F8F8",
        themegray: "#F6F6F6",
        borderColor: "#DDDDDD",
        themeText: "#FFFFFF",
        themePlaceholder: "#000000",
        themeRed: "#EE4036",
        themebackground: "#F1F1F1",
        bgForm: "#EEF1FA",
        statusOngoing: "#FF745A",
        statusSend: "#00994D",
        crossColor: "#E11111",
        themeTeal: "#00E4C2",
        themeRed: "#FF0000",
        inputPlaceholder: "#575656",
        themeRed: "#F30B0B",
        cardColorActive: "#00DDBF",
        cardBgColor: "#FBFBFB",
        customGradientBg:
          "linear-gradient(180deg ,rgba(217, 217, 217, 0.4) 0%,rgba(255, 255, 255, 0.6) 50%)",
      },
      colors: {
        theme: "#00538C",
        cardTheme: "#F4F4F4",
        baseColor: "#F8F8F8",
        themegray: "#F6F6F6",
        borderColor: "#DDDDDD",
        themeText: "#FFFFFF",
        themePlaceholder: "#000000",
        themeRed: "#EE4036",
        themebackground: "#F1F1F1",
        bgForm: "#EEF1FA",
        statusOngoing: "#FF745A",
        statusSend: "#00994D",
        crossColor: "#E11111",
        themeTeal: "#00E4C2",
        themeRed: "#FF0000",
        inputPlaceholder: "#575656",
        themeRed: "#F30B0B",
        cardColorActive: "#00DDBF",
        cardBgColor: "#FBFBFB",
        customGradientBg:
          "linear-gradient(180deg,rgba(217, 217, 217, 0.4) 0%,rgba(255, 255, 255, 0.6) 50%)",
      },
      boxShadow: {
        cardShadow: "0px 4px 20px 0px #00000033",
      },
    },
  },
  plugins: [],
};
